/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/Aside.vue')['default']
    CardTask: typeof import('./src/components/CardTask.vue')['default']
    DoneTask: typeof import('./src/components/views/DoneTask.vue')['default']
    DooList: typeof import('./src/components/DooList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListComments: typeof import('./src/components/ListComments.vue')['default']
    ListProject: typeof import('./src/components/ListProject.vue')['default']
    ListSections: typeof import('./src/components/ListSections.vue')['default']
    ListTask: typeof import('./src/components/ListTask.vue')['default']
    MenuItem: typeof import('./src/components/MenuItem.vue')['default']
    MenuSetting: typeof import('./src/components/MenuSetting.vue')['default']
    ModalCard: typeof import('./src/components/ModalCard.vue')['default']
    ModalProject: typeof import('./src/components/ModalProject.vue')['default']
    ModalTask: typeof import('./src/components/ModalTask.vue')['default']
    MyProject: typeof import('./src/components/views/MyProject.vue')['default']
    NewTask: typeof import('./src/components/views/NewTask.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingProject: typeof import('./src/components/views/SettingProject.vue')['default']
    SettingTask: typeof import('./src/components/SettingTask.vue')['default']
    TodayTask: typeof import('./src/components/views/TodayTask.vue')['default']
  }
}
