export enum MenuAction {
  AddAbove = "addAbove",
  AddBelow = "addBelow",
  Edit = "edit",
  AddToFavorites = "addToFavorites",
  RemoveFromFavorites = "removeFromFavorites",
  Duplicate = "duplicate",
  GeneralAccess = "generalAccess",
  CopyLink = "copyLink",
  SaveAsTemplate = "saveAsTemplate",
  ViewTemplate = "viewTemplate",
  ImportCSV = "importCSV",
  ExportCSV = "exportCSV",
  AddByEmail = "addByEmail",
  CalendarFeed = "calendarFeed",
  ActionLog = "actionLog",
  AddExtension = "addExtension",
  Archive = "archive",
  Delete = "delete",
}
